import "./globals.css";
import NavBar from "@/components/ui/NavBar";
import Footer from "@/components/ui/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="h-full">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className="min-h-full flex flex-col">
        <NavBar />
        <main className="grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
